#' Embryo dynamics at CpG sets measured in Guo et al data
#'
#' Calculates proportion of CpGs with intermediate methylation
#'    (10-90%) at ICM and embryonic liver stages from Guo RRBS dataset
#'    'covered' cgs are those covered at 10x at 
#'    BOTH stages
#'    ENID/EMPH GUO data DFs generated by NJK:26/11/18)

#'
#'
#' @param annot.gr 
#' @param plot.params 
#'
#' @return NULL
plot_Guo_intermediate_meth = function(annot.gr=NULL,plot.save=FALSE,plot.params=NULL){
  
  library(tidyverse)
  library(GenomicRanges)
  
  # PARAMS
  n.bootstrap = 1000
  cat('n.bootstrap=',n.bootstrap,'\n\n')
  
  # find Guo loci overlapping array.bgd
  Guo.RRBS <- readRDS('/data/Guo_embryo/Guo.RRBS.10x.RDS')[,c()] # cg index is the row in this df
  olaps = findOverlaps(Guo.RRBS,annot.gr)
  cat(length(olaps),'Guo CpGs overlap array background\n')
  
  # load Guo ICM/liver data and filter on array content
  Guo.RRBS.transitions.ICM_Embryo <- readRDS('/data/Guo_embryo/Guo.RRBS.transitions.ICM_Embryo.RDS')
  Guo.icm.liver.olap.array.tbl = 
    as_tibble(
      Guo.RRBS.transitions.ICM_Embryo[Guo.RRBS.transitions.ICM_Embryo$index %in% queryHits(olaps),]
    )
  Guo.icm.liver.olap.array.tbl = 
    Guo.icm.liver.olap.array.tbl %>%
      select(icm.meth=methy.a,liver.meth=methy.b,index)
  rm(Guo.RRBS.transitions.ICM_Embryo)
  
  # AGGREGATE ACROSS CpGs. 
  # This is necessary since individual CpGs ('index') can appear multple
  # times if they are covered in multiple replicates
  cat('averaging ICM/embryonic liver methylation levels across replicates...\n')
  icm.liver.rep.mean.tbl = Guo.icm.liver.olap.array.tbl %>% 
    group_by(index) %>%
    summarise(
      n.replicates = n(),
      ICM=mean(icm.meth),
      liver=mean(liver.meth)
    )
  cat('done\n\n')
  
  # categorise by intermediate methylation
  icm.liver.rep.mean.tbl$ICM.inter = FALSE
  icm.liver.rep.mean.tbl[(icm.liver.rep.mean.tbl$ICM<0.9 & icm.liver.rep.mean.tbl$ICM>0.1),'ICM.inter'] = TRUE
  icm.liver.rep.mean.tbl$liver.inter = FALSE
  icm.liver.rep.mean.tbl[(icm.liver.rep.mean.tbl$liver<0.9 & icm.liver.rep.mean.tbl$liver>0.1),'liver.inter'] = TRUE
  # add genomic locations
  icm.liver.gr = Guo.RRBS[icm.liver.rep.mean.tbl$index]
  mcols(icm.liver.gr) = icm.liver.rep.mean.tbl
  
  # add annotation data to Guo ICM / liver data
  olaps.icm.liver.annot = findOverlaps(annot.gr,icm.liver.gr)
  mcols(icm.liver.gr) = cbind(
    mcols(icm.liver.gr)[subjectHits(olaps.icm.liver.annot),],
    mcols(annot.gr)[queryHits(olaps.icm.liver.annot),]
  )
  
  # summarise CpGs covered at 10x by Guo
  cat(length(icm.liver.gr),'Guo cgs overlap array background at 10x (ICM and emb liver)\n')
  cat('coverage of loci of interest as follows:\n')
  print(
    summary(
      as.data.frame(mcols(icm.liver.gr)) %>%
        select(cpg,replicated,ME,ctrl)
    )
  )
  
  # generate propotions of intermediate methylation
  icm.liver.df = data.frame(mcols(icm.liver.gr)) %>%
    select(discovery,replicated,ME,ctrl,ICM.inter,liver.inter)
  
  
  prop.data = data.frame(
    prop.inter.icm = numeric(),
    prop.inter.icm.lower = numeric(),
    prop.inter.icm.upper = numeric(),
    prop.inter.liver = numeric(),
    prop.inter.liver.lower = numeric(),
    prop.inter.liver.upper = numeric()
  )
  
  cat('generating bootstrap CIs for proportions...\n')
  
  for (test.set in c('replicated','ME','ctrl','array')){
  # for (test.set in c('discovery.cgs','replicated','ME','array')){
      
    if (test.set=='array'){
      test.df = icm.liver.df  
    } else {
      test.df = icm.liver.df[icm.liver.df[,test.set],]  
    }
    n.tested = nrow(test.df) # number of loci tested
    
    prop.data[test.set,] = c(
      prop.inter.icm = sum(test.df$ICM.inter)/n.tested,
      prop.inter.icm.lower = alpha.quantiles.lower(bootstrap.prop(test.df$ICM.inter,n.bootstrap),0.05),
      prop.inter.icm.upper = alpha.quantiles.upper(bootstrap.prop(test.df$ICM.inter,n.bootstrap),0.05),
      prop.inter.liver = sum(test.df$liver.inter)/n.tested,
      prop.inter.liver.lower = alpha.quantiles.lower(bootstrap.prop(test.df$liver.inter,n.bootstrap),0.05),
      prop.inter.liver.upper = alpha.quantiles.upper(bootstrap.prop(test.df$liver.inter,n.bootstrap),0.05)
    )
  
  }
  
  print(prop.data)
  
  
  # PLOT
  prop.data$set = row.names(prop.data)
  icm.data = cbind(
    stage='ICM',
    prop.data[,c(1:3,7)]
  )
  colnames(icm.data) = c('stage','prop.inter','lower','upper','set')
  liver.data = 
    cbind(
      stage='liver',
      prop.data[,c(4:7)]
  )
  colnames(liver.data) = c('stage','prop.inter','lower','upper','set')
  all.data = rbind(icm.data,liver.data)
  
  # plot order
  all.data$set = 
    recode_factor(all.data$set,
          'replicated' = 'SoC-CpGs',
          'ME' = 'all MEs',
          'ctrl' = 'matched\ncontrols',
          'array' = 'array\nbackground'
    )
  all.data$stage = 
    recode_factor(all.data$stage,
          'ICM' = 'ICM',
          'liver' = 'emb\nliver'
    )
  
  plt = ggplot(all.data, aes(x=stage)) +
    facet_wrap(~set, nrow = 1) +
    geom_errorbar(aes(ymax=prop.inter, ymin=prop.inter), position = position_dodge(width = 0.5)) +
    geom_errorbar(aes(ymax=lower, ymin=upper), position = position_dodge(width = 0.5), width=0.5) +
    geom_point(aes(y=prop.inter), position = position_dodge(width = 0.5), fill="white", shape=23, size=0.5) +
    theme_bw(base_size = 10) +
    theme(
      panel.grid.major.x=element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.x=element_text(colour='black',angle = 30),
      axis.text.y=element_text(colour='black'),
      axis.title.x = element_blank(),
      # axis.title=element_text(face="bold"),
      panel.grid.minor.x=element_blank(),
      strip.background = element_rect(colour = "black", fill = "white"),
      legend.position = 'none'
    ) +
    scale_y_continuous(breaks = c(0.25,0.5,0.75),labels = scales::percent_format(accuracy = 1)) +
    # scale_y_continuous(labels=scales::percent_format(accuracy = 2),breaks = c(0.25,0.5,0.75)) +
    labs(
      y='% intermediately methylated'
    )
  
  print(plt)
  
  if (plot.save){
    ggsave(filename = paste0(plot.params$dir,"guo_transition.pdf"),
           dpi = plot.params$dpi,width = 1.2*plot.params$width,height = plot.params$height,units = 'cm'
    )
  }
  
}



#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#' Plot bootstrapped sperm hypomethylation proportions
#' 
#' Also plot mean betas stratified by sperm hypomethylation status
#' and sperm hypo CpGs stratified by oo-gDMR status
#'
#' @param annot.gr 
#' @param plot.save 
#' @param plot.params 
#'
#' @return
plot_Okae_sperm_hypomethylation = function(annot.gr=NULL,plot.save=FALSE,plot.params=NULL){
  
  library(tidyverse)
  library(GenomicRanges)
  # PARAMS
  n.bootstrap = 1000
  cat('n.bootstrap=',n.bootstrap,'\n\n')
  
  # LOAD COMPLETE Okae DATA
  Okae.Sperm_Oocyte.gr = readRDS('/data/Okae_sperm/Okae.Gamete_methy.mincov_10.RDS')
  Okae.Sperm_Oocyte.gr$Oocyte.1 = NULL
  Okae.Sperm_Oocyte.gr$Oocyte.2 = NULL
  Okae.Sperm_Oocyte.gr$Guo.idx=NULL
  
  # filter to array background
  olaps.okae.array = findOverlaps(Okae.Sperm_Oocyte.gr,annot.gr)
  okae.sperm.gr = Okae.Sperm_Oocyte.gr[queryHits(olaps.okae.array)]
  
  # AGGREGATE ACROSS REPLICATES
  okae.sperm.gr$sperm = rowMeans(select(as.data.frame(mcols(okae.sperm.gr)),Sperm.1,Sperm.2,Sperm.3),na.rm = T)
  okae.sperm.gr = okae.sperm.gr[!is.na(okae.sperm.gr$sperm)]
  cat(length(okae.sperm.gr),'Okae sperm cgs with minimum 10x mapping to array background identified\n')
  # categorise by sperm hypomethylation
  okae.sperm.gr$sperm.hypo = FALSE
  okae.sperm.gr[okae.sperm.gr$sperm<=0.1]$sperm.hypo = TRUE
  
  # add sperm hypo annot to annot.gr for downstream analysis
  annot.gr$sperm.hypo = NA
  olaps.annot.gr = findOverlaps(annot.gr,okae.sperm.gr)
  annot.gr[queryHits(olaps.annot.gr)]$sperm.hypo = okae.sperm.gr[subjectHits(olaps.annot.gr)]$sperm.hypo
  
  annot.df = as.data.frame(annot.gr) %>%
    filter(!is.na(sperm.hypo)) %>%
    select(cpg,replicated,ME,ctrl,enid.mean.beta,emph.mean.beta,oo.gDMR,sperm.hypo)
  
  
  # summarise CpGs covered at 10x by Okae
  cat(nrow(annot.df),'Okae cgs overlap array background at 10x\n')
  cat('coverage of loci of interest as follows:\n')
  print(
    summary(annot.df)
  )

  prop.data = data.frame(
    prop.sperm.hypo = numeric(),
    prop.sperm.hypo.lower = numeric(),
    prop.sperm.hypo.upper = numeric()
  )
  
  cat('generating bootstrap CIs for proportions...\n')
  
  for (test.set in c('replicated','ME','ctrl','array')){

    if (test.set=='array'){
      test.df = annot.df  
    } else {
      test.df = annot.df[annot.df[[test.set]],]  
    }
    n.tested = sum(!is.na(test.df$sperm.hypo)) # number of loci tested
    
    prop.data[test.set,] = c(
      prop.sperm.hypo = sum(test.df$sperm.hypo,na.rm = T)/n.tested,
      prop.sperm.hypo.lower = alpha.quantiles.lower(bootstrap.prop(test.df$sperm.hypo[!is.na(test.df$sperm.hypo)],n.bootstrap),0.05),
      prop.sperm.hypo.upper = alpha.quantiles.upper(bootstrap.prop(test.df$sperm.hypo[!is.na(test.df$sperm.hypo)],n.bootstrap),0.05)
    )
    
  }
  
  print(prop.data)

  # PLOT
  prop.data$set = row.names(prop.data)
  colnames(prop.data) = c('prop.hypo','lower','upper','set')
  
  # plot order
  prop.data$set = 
    recode_factor(prop.data$set,
        'replicated' = 'SoC-CpGs',
        'ME' = 'all MEs',
        'ctrl' = 'matched\ncontrols',
        'array' = 'array\nbackground'
    )
  
  plt = ggplot(prop.data, aes(x=set)) +
    geom_errorbar(aes(ymax=prop.hypo, ymin=prop.hypo)) +
    geom_errorbar(aes(ymax=lower, ymin=upper), width=0.5) +
    geom_point(aes(y=prop.hypo), fill="white", shape=23) +
    theme_bw(base_size = 10) +
    theme(
      panel.grid.major.x=element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.x=element_text(colour='black'),
      axis.text.y=element_text(colour='black'),
      axis.title.x = element_blank(),
      panel.grid.minor.x=element_blank(),
      strip.background = element_rect(colour = "black", fill = "white"),
      legend.position = 'none'
    ) +
    scale_y_continuous(labels=scales::percent_format(accuracy = 2)) +
    labs(
      y='% hypomethylated in sperm'
    )
  
  print(plt)
  
  if (plot.save){
    ggsave(filename = paste0(plot.params$dir,"okae_sperm_hypo.pdf"),
         dpi = plot.params$dpi,width = plot.params$width,height = plot.params$height,units = 'cm'
    )
  }
  

  # plot mean betas stratified by sperm hypomethylation
  plot.df = annot.df %>%
    select(cpg,replicated,ME,oo.gDMR,enid.mean.beta,emph.mean.beta,sperm.hypo) %>%
    gather(enid.mean.beta,emph.mean.beta,key = 'cohort',value = 'mean.beta')
  
  # replicate to account for overlapping groups
  plot.df = rbind(
    cbind(
      plot.df[plot.df$ME & plot.df$replicated,],
      locus = 'SoC-CpGs\nMEs'
    ),
    cbind(
      plot.df[plot.df$replicated & !plot.df$ME,],
      locus = 'SoC-CpGs\nnon-MEs'
    ),
    cbind(
      plot.df[plot.df$ME,],
      locus = 'all MEs'
    ),
    cbind(
      plot.df,
      locus = 'array\nbackground'
    )
  )
  
  # specify plot order
  plot.df$locus = recode_factor(plot.df$locus,
    'SoC-CpGs\nMEs'='SoC-CpGs\nMEs',
    'SoC-CpGs\nnon-MEs'='SoC-CpGs\nnon-MEs',
    'all MEs'='all MEs',
    'array\nbackground'='array\nbackground'
  )
  plot.df$sperm.hypo = recode_factor(as.factor(plot.df$sperm.hypo),
    'TRUE' = 'hypo sperm',
    'FALSE' = 'not hypo sperm'
  )
  
  print(
    ggplot(data=plot.df,aes(x=locus,y=100*mean.beta,colour=locus)) +
      geom_jitter(width=0.1,alpha=0.5, size=0.5) +
      geom_violin(colour='black',alpha=0) +
      facet_wrap(~sperm.hypo,ncol = 1,strip.position = 'right') +
      theme_bw() +
      scale_colour_manual("locus",values=c('red','royalblue2','pink','lightgrey','darkgrey')) +
      theme_bw(base_size = 10) +
      theme(
        axis.text.x = element_text(angle=30,hjust = 1,colour='black',size='8'),
        legend.position="none",
        strip.background = element_rect(fill = 'white')
      ) +
      labs(
        x='',
        y='mean methylation (%)'
      )
  )

  if (plot.save){
    ggsave(filename = paste0(plot.params$dir,"mean.beta_by_sperm_hypo.png"),
           dpi = plot.params$dpi,width = 1.2*plot.params$width,height = 1.2*plot.params$height,units = 'cm'
    )
  }
  
  # repeat for regions ALSO methylated in oocytes (i.e. oo.gDMRs); and separate IGF1R etc
  plot.df.sperm.hypo = filter(plot.df,sperm.hypo=='hypo sperm')
  
  # distinguish IGF1R and 14q32
  plot.df.sperm.hypo$colour.label = as.character(plot.df.sperm.hypo$locus)
  igf1r.cgs = filter(as.data.frame(mcols(annot.gr)),UCSC_RefGene_Name=='IGF1R' & replicated)$cpg
  meg3.cg = 'cg20030294'
  plot.df.sperm.hypo[
    (plot.df.sperm.hypo$cpg %in% c(igf1r.cgs,meg3.cg) & !plot.df.sperm.hypo$locus=='array\nbackground'),
    'colour.label'] = 'replicated\nIGF1R/14q32'
  
  plot.df.sperm.hypo$oo.gDMR = recode_factor(as.factor(plot.df.sperm.hypo$oo.gDMR),
     'TRUE' = 'oocyte\ngDMR',
     'FALSE' = 'not oocyte\ngDMR'
  )
  
  plot.df.sperm.hypo$locus = 
    recode_factor(plot.df.sperm.hypo$locus, 
                  'SoC-CpGs\nMEs' = 'SoC-CpGs\nMEs',
                  'SoC-CpGs\nnon-MEs' = 'SoC-CpGs\nnon-MEs',
                  'all MEs' = 'all MEs',
                  'array\nbackground' = 'array\nbackground'
    )

  print(
    ggplot(data=plot.df.sperm.hypo,aes(x=locus,y=100*mean.beta,colour=colour.label)) +
      geom_jitter(aes(shape=colour.label,size=colour.label),width=0.1,alpha=0.5) +
      geom_violin(colour='black',alpha=0) +
      facet_wrap(~oo.gDMR,ncol = 1,strip.position = 'right') +
      theme_bw() +
      scale_colour_manual("locus",
          breaks=c('SoC-CpGs\nMEs','replicated\nIGF1R/14q32','SoC-CpGs\nnon-MEs','all MEs','array\nbackground'),
          values=c('red','darkgreen','royalblue2','pink','lightgrey'),
          limits=c('SoC-CpGs\nMEs','replicated\nIGF1R/14q32','SoC-CpGs\nnon-MEs','all MEs','array\nbackground')
      ) +
      scale_shape_manual("locus",
         breaks=c('SoC-CpGs\nMEs','replicated\nIGF1R/14q32','SoC-CpGs\nnon-MEs','all MEs','array\nbackground'),
         values=c(16,17,16,16,16),
         limits=c('SoC-CpGs\nMEs','replicated\nIGF1R/14q32','SoC-CpGs\nnon-MEs','all MEs','array\nbackground')
      ) +
      scale_size_manual("locus",
        breaks=c('SoC-CpGs\nMEs','replicated\nIGF1R/14q32','SoC-CpGs\nnon-MEs','all MEs','array\nbackground'),
        values=c(0.5,0.75,0.5,0.5,0.5),
        limits=c('SoC-CpGs\nMEs','replicated\nIGF1R/14q32','SoC-CpGs\nnon-MEs','all MEs','array\nbackground')
      ) +
      theme_bw(base_size = 10) +
      theme(
        axis.text.x = element_text(angle=30,hjust = 1,colour='black',size='8'),
        legend.position="none",
        strip.background = element_rect(fill = 'white')
      ) +
      labs(
        x='',
        y='mean Gambia\ncohorts methylation (%)'
      )
  )
  
  if (plot.save){
    ggsave(filename = paste0(plot.params$dir,"mean.beta_sperm.hypo_by_oo.gDMR_w_IGF1R.png"),
           dpi = plot.params$dpi,width = 1.2*plot.params$width,height = 1.2*plot.params$height,units = 'cm'
    )
  }
  
}

